### ISSUE TITLE
Unable to provision non-sparse volumes

### ISSUE THREAD

**Issue by santimar** [hpe-storage/truenas-csp#49]
I followed the tutorial on [INSTALL.md](https://github.com/hpe-storage/truenas-csp/blob/master/INSTALL.md) and installed the provider via helm.

At the last step I'm creating the storage class like this:
```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
  name: hpe-storageclass
provisioner: csi.hpe.com
parameters:
  csi.storage.k8s.io/controller-expand-secret-name: truenas-secret
  csi.storage.k8s.io/controller-expand-secret-namespace: hpe-storage
  csi.storage.k8s.io/controller-publish-secret-name: truenas-secret
  csi.storage.k8s.io/controller-publish-secret-namespace: hpe-storage
  csi.storage.k8s.io/node-publish-secret-name: truenas-secret
  csi.storage.k8s.io/node-publish-secret-namespace: hpe-storage
  csi.storage.k8s.io/node-stage-secret-name: truenas-secret
  csi.storage.k8s.io/node-stage-secret-namespace: hpe-storage
  csi.storage.k8s.io/provisioner-secret-name: truenas-secret
  csi.storage.k8s.io/provisioner-secret-namespace: hpe-storage
  csi.storage.k8s.io/fstype: xfs
  allowOverrides: compression,deduplication,volblocksize,sync
  root: pool1/mypool
  sparse: 'false'
  description: my custom description
reclaimPolicy: Delete
allowVolumeExpansion: true
```
The SC should create non sparse volumes by default.

I then create a PVC with the SC
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: hpe-storageclass
  resources:
    requests:
      storage: 10Gi
```

The PV is created, but on TrueNAS UI i see `Provisioning Type: Sparse` instead of `Provisioning Type: Thick`
![image](https://github.com/hpe-storage/truenas-csp/assets/22396529/79aff28f-ac24-4428-b1e9-29b2c10bdbc0)

Am I missing something?
