### ISSUE TITLE
Error "null not allowed" with truenas scale 24.10.2.1

### ISSUE THREAD

**Issue by ffais** [hpe-storage/truenas-csp#80]
I tried to use truenas-csp with Truenas SCAle 24.10.2.1 but the pvc remains in pending stete and I receive the following error:

```
Wed, 16 Apr 2025 11:46:03 +0000 backend 7 DEBUG Falcon Response (to HPE CSI): 500 Internal Server Error
Wed, 16 Apr 2025 11:46:03 +0000 backend 7 DEBUG Last backend requests Response: 422 Unprocessable Entity
Wed, 16 Apr 2025 11:46:11 +0000 backend 8 DEBUG Composed query: {}
Wed, 16 Apr 2025 11:46:11 +0000 backend 8 DEBUG API Key detected. Will use token authentication.
Wed, 16 Apr 2025 11:46:11 +0000 backend 8 DEBUG TrueNAS GET request URI: core/ping
Wed, 16 Apr 2025 11:46:11 +0000 backend 8 DEBUG TrueNAS response: "pong"
Wed, 16 Apr 2025 11:46:11 +0000 backend 8 DEBUG API fetch caught 1 item
Wed, 16 Apr 2025 11:46:11 +0000 backend 8 DEBUG HPE CSI Request <==============================>
Wed, 16 Apr 2025 11:46:11 +0000 backend 8 DEBUG          uri: http://truenas-csp-svc:8080/containers/v1/volumes?name=pvc-59e64536-5d60-435d-820d-ccab8a9555db
Wed, 16 Apr 2025 11:46:11 +0000 backend 8 DEBUG         body: None
Wed, 16 Apr 2025 11:46:11 +0000 backend 8 DEBUG        query: name=pvc-59e64536-5d60-435d-820d-ccab8a9555db
Wed, 16 Apr 2025 11:46:11 +0000 backend 8 DEBUG       method: GET
Wed, 16 Apr 2025 11:46:11 +0000 backend 8 DEBUG content_type: application/json
Wed, 16 Apr 2025 11:46:11 +0000 backend 8 DEBUG      headers: {"HOST": "truenas-csp-svc:8080", "USER-AGENT": "Go-http-client/1.1", "CONNECTION": "close", "ACCEPT": "application/json", "CONTENT-TYPE": "application/json", "X-ARRAY-IP": "10.233.0.11", "X-AUTH-TOKEN": "*****", "ACCEPT-ENCODING": "gzip"}
Wed, 16 Apr 2025 11:46:11 +0000 backend 8 DEBUG Composed query: {'query-filters': [['name', '$', '/pvc-59e64536-5d60-435d-820d-ccab8a9555db']], 'query-options': {}}
Wed, 16 Apr 2025 11:46:11 +0000 backend 8 DEBUG API Key detected. Will use token authentication.
Wed, 16 Apr 2025 11:46:11 +0000 backend 8 DEBUG TrueNAS GET request URI: pool/dataset
Wed, 16 Apr 2025 11:46:12 +0000 backend 8 DEBUG TrueNAS response: []
Wed, 16 Apr 2025 11:46:12 +0000 backend 8 DEBUG API fetch caught 0 items (last resort)
Wed, 16 Apr 2025 11:46:12 +0000 backend 8 ERROR Not found: Volume with name pvc-59e64536-5d60-435d-820d-ccab8a9555db not found.
Wed, 16 Apr 2025 11:46:12 +0000 backend 8 DEBUG Falcon Response (to HPE CSI): 404 Not Found
Wed, 16 Apr 2025 11:46:12 +0000 backend 8 DEBUG Last backend requests Response: 200 OK
Wed, 16 Apr 2025 11:46:12 +0000 backend 8 DEBUG Composed query: {}
Wed, 16 Apr 2025 11:46:12 +0000 backend 8 DEBUG API Key detected. Will use token authentication.
Wed, 16 Apr 2025 11:46:12 +0000 backend 8 DEBUG TrueNAS GET request URI: core/ping
Wed, 16 Apr 2025 11:46:12 +0000 backend 8 DEBUG TrueNAS response: "pong"
Wed, 16 Apr 2025 11:46:12 +0000 backend 8 DEBUG API fetch caught 1 item
Wed, 16 Apr 2025 11:46:12 +0000 backend 8 DEBUG HPE CSI Request <==============================>
Wed, 16 Apr 2025 11:46:12 +0000 backend 8 DEBUG          uri: http://truenas-csp-svc:8080/containers/v1/volumes
Wed, 16 Apr 2025 11:46:12 +0000 backend 8 DEBUG         body: {'name': 'pvc-59e64536-5d60-435d-820d-ccab8a9555db', 'size': 21474836480, 'config': {'allow_overrides': 'sparse,compression,deduplication,volblocksize,sync,description', 'auth_networks': '10.233.0.1/24', 'csi.storage.k8s.io/pv/name': 'pvc-59e64536-5d60-435d-820d-ccab8a9555db', 'csi.storage.k8s.io/pvc/name': 'test', 'csi.storage.k8s.io/pvc/namespace': 'default', 'host_encryption': 'false', 'multi_initiator': False, 'root': 'big/kubernetes'}, 'volume_group_id': ''}
Wed, 16 Apr 2025 11:46:12 +0000 backend 8 DEBUG        query: 
Wed, 16 Apr 2025 11:46:12 +0000 backend 8 DEBUG       method: POST
Wed, 16 Apr 2025 11:46:12 +0000 backend 8 DEBUG content_type: application/json
Wed, 16 Apr 2025 11:46:12 +0000 backend 8 DEBUG      headers: {"HOST": "truenas-csp-svc:8080", "USER-AGENT": "Go-http-client/1.1", "CONNECTION": "close", "CONTENT-LENGTH": "446", "ACCEPT": "application/json", "CONTENT-TYPE": "application/json", "X-ARRAY-IP": "10.233.0.11", "X-AUTH-TOKEN": "*****", "ACCEPT-ENCODING": "gzip"}
Wed, 16 Apr 2025 11:46:12 +0000 backend 8 DEBUG API Key detected. Will use token authentication.
Wed, 16 Apr 2025 11:46:12 +0000 backend 8 DEBUG TrueNAS POST request URI: pool/dataset
Wed, 16 Apr 2025 11:46:12 +0000 backend 8 DEBUG TrueNAS request: {'type': 'VOLUME', 'comments': 'Dataset created by HPE CSI Driver for Kubernetes as pvc-59e64536-5d60-435d-820d-ccab8a9555db in default from test', 'name': 'big/kubernetes/pvc-59e64536-5d60-435d-820d-ccab8a9555db', 'volsize': '21474836480', 'volblocksize': '8K', 'sparse': True, 'deduplication': 'OFF', 'sync': 'STANDARD', 'compression': 'LZ4'}
Wed, 16 Apr 2025 11:46:12 +0000 backend 8 DEBUG TrueNAS response: {'path': [{'message': 'null not allowed', 'errno': 22}]}
Wed, 16 Apr 2025 11:46:12 +0000 backend 8 ERROR Backend Request (POST) Exception: 422 Unprocessable Entity: Traceback (most recent call last):
  File "/app/backend.py", line 446, in post
    self.req_backend.raise_for_status()
  File "/app/lib/python3.12/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 422 Client Error: Unprocessable Entity for url: https://10.233.0.11/api/v2.0/pool/dataset

Wed, 16 Apr 2025 11:46:12 +0000 backend 8 ERROR Bad Request: TrueNAS API returned: {
 "path": [
  {
   "message": "null not allowed",
   "errno": 22
  }
 ]
}
Wed, 16 Apr 2025 11:46:12 +0000 backend 8 DEBUG Falcon Response (to HPE CSI): 500 Internal Server Error
Wed, 16 Apr 2025 11:46:12 +0000 backend 8 DEBUG Last backend requests Response: 422 Unprocessable Entity
```
I've installed truenas-csp with latest helm chart.

StorageClass:

```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
  name: true-storageclass
provisioner: csi.hpe.com
parameters:
  csi.storage.k8s.io/controller-expand-secret-name: truenas-secret
  csi.storage.k8s.io/controller-expand-secret-namespace: true-storage
  csi.storage.k8s.io/controller-publish-secret-name: truenas-secret
  csi.storage.k8s.io/controller-publish-secret-namespace: true-storage
  csi.storage.k8s.io/node-publish-secret-name: truenas-secret
  csi.storage.k8s.io/node-publish-secret-namespace: true-storage
  csi.storage.k8s.io/node-stage-secret-name: truenas-secret
  csi.storage.k8s.io/node-stage-secret-namespace: true-storage
  csi.storage.k8s.io/provisioner-secret-name: truenas-secret
  csi.storage.k8s.io/provisioner-secret-namespace: true-storage
  csi.storage.k8s.io/fstype: xfs
  allowOverrides: sparse,compression,deduplication,volblocksize,sync,description
  authNetworks: 10.233.0.1/24
  root: big/kubernetes
reclaimPolicy: Delete
allowVolumeExpansion: true

```

Secret:
```
apiVersion: v1
kind: Secret
metadata:
  name: truenas-secret
  namespace: true-storage
stringData:
  serviceName: truenas-csp-svc
  servicePort: "8080"
  username: kubernetes
  password: "api-key"
  backend: 10.233.0.11

```
