### ISSUE TITLE
Use nfsResources Storage Class with nonroot container

### ISSUE THREAD

**Issue by ffais** [hpe-storage/truenas-csp#82]
If I try to use a Storage Class with nfsResources set to true inside a nonroot container, a permission denies is returned.

This is the output:
```
~ $ touch test/file
touch: test/file: Permission denied
```
Those are the manifests:
```
apiVersion: v1
kind: Pod
metadata:
  name: "test-many1"
  namespace: default
  labels:
    app: "test-many1"
spec:
  securityContext:
    runAsUser: 10000
    runAsGroup: 10000
    fsGroup: 10000
  containers:
  - name: test-many
    image: "busybox:latest"
    command: [ "/bin/sh", "-c", "--" ]
    args: [ "while true; do sleep 30; done;" ]
    resources:
      limits:
        cpu: 200m
        memory: 500Mi
      requests:
        cpu: 100m
        memory: 200Mi
    ports:
    - containerPort:  80
      name:  http
    volumeMounts:
    - name: localtime
      mountPath: /test
  volumes:
    - name: localtime
      persistentVolumeClaim:
        claimName: test-many
  restartPolicy: Always
---
apiVersion: v1
kind: Pod
metadata:
  name: "test-many2"
  namespace: default
  labels:
    app: "test-many2"
spec:
  securityContext:
    runAsUser: 10000
    runAsGroup: 10000
    fsGroup: 10000
  containers:
  - name: test-many
    image: "busybox:latest"
    command: [ "/bin/sh", "-c", "--" ]
    args: [ "while true; do sleep 30; done;" ]
    resources:
      limits:
        cpu: 200m
        memory: 500Mi
      requests:
        cpu: 100m
        memory: 200Mi
    ports:
    - containerPort:  80
      name:  http
    volumeMounts:
    - name: localtime
      mountPath: /test
  volumes:
    - name: localtime
      persistentVolumeClaim:
        claimName: test-many
  restartPolicy: Always
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-many
  namespace: default
  labels:
    app: test-many
spec:
  storageClassName: true-storageclass-system-nfs
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
  name: true-storageclass-system-nfs
provisioner: csi.hpe.com
parameters:
  csi.storage.k8s.io/controller-expand-secret-name: truenas-secret
  csi.storage.k8s.io/controller-expand-secret-namespace: true-storage
  csi.storage.k8s.io/controller-publish-secret-name: truenas-secret
  csi.storage.k8s.io/controller-publish-secret-namespace: true-storage
  csi.storage.k8s.io/node-publish-secret-name: truenas-secret
  csi.storage.k8s.io/node-publish-secret-namespace: true-storage
  csi.storage.k8s.io/node-stage-secret-name: truenas-secret
  csi.storage.k8s.io/node-stage-secret-namespace: true-storage
  csi.storage.k8s.io/provisioner-secret-name: truenas-secret
  csi.storage.k8s.io/provisioner-secret-namespace: true-storage
  csi.storage.k8s.io/fstype: xfs
  nfsResources: "true"
  allowOverrides: sparse,compression,deduplication,volblocksize,sync,description  
  authNetworks: 192.233.0.1/24
  root: small/kubernetes
reclaimPolicy: Delete
allowVolumeExpansion: true

```

**Comment by ffais** [comment]
@datamattsson Following your advice I found a solution that works for my use case. I configured the fsMode parameter to 0777, this allows me to use the same volume even with containers that use different users. For those who do not need to support different users, simply configure fsOwner with the appropriate user ID.

```
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
  name: true-storageclass-system-nfs
provisioner: csi.hpe.com
parameters:
  csi.storage.k8s.io/controller-expand-secret-name: truenas-secret
  csi.storage.k8s.io/controller-expand-secret-namespace: true-storage
  csi.storage.k8s.io/controller-publish-secret-name: truenas-secret
  csi.storage.k8s.io/controller-publish-secret-namespace: true-storage
  csi.storage.k8s.io/node-publish-secret-name: truenas-secret
  csi.storage.k8s.io/node-publish-secret-namespace: true-storage
  csi.storage.k8s.io/node-stage-secret-name: truenas-secret
  csi.storage.k8s.io/node-stage-secret-namespace: true-storage
  csi.storage.k8s.io/provisioner-secret-name: truenas-secret
  csi.storage.k8s.io/provisioner-secret-namespace: true-storage
  csi.storage.k8s.io/fstype: xfs
  nfsResources: "true"
  fsMode: "0777"
  allowOverrides: sparse,compression,deduplication,volblocksize,sync,description  
  authNetworks: 192.233.0.1/24
  root: small/kubernetes
reclaimPolicy: Delete
allowVolumeExpansion: true
```
